### ISSUE TITLE
Use of static ScriptEngine not thread safe if using default Bindings

### ISSUE THREAD

**Issue by St0n3Gh0st** [jshaptic/jshint-javaport#4]
See the Lexer.class creation of ScriptEngine:

`private static final ScriptEngine jsEngine = new ScriptEngineManager().getEngineByName("nashorn");`

As described [here](https://stackoverflow.com/questions/30140103/should-i-use-a-separate-scriptengine-and-compiledscript-instances-per-each-threa/30159424#30159424), the ScriptEngine itself is thread safe, but by using the default Bindings (instead of creating a new Bindings per thread), the overall execution is not thread safe.

We believe this is causing unpredictable errors when we use this in a multi-threaded environment.

**Comment by jshaptic** [comment]
Thanks @St0n3Gh0st for the report!

You are correct that using ScriptEngine with default Bindings is not thread safe and I will accept PR provided by @abonstu.

However, make a note, that this project currently isn't working correctly in a multi-threaded environment, not because of the default Bindings, but mostly because of the current design and State object in particular. I was trying to run tests in parallel mode and it wasn't working as expected. I have plans to refactor it and make it work in multi-threaded environment, but I don't when it will happen.

**Comment by jshaptic** [comment]
Pull request #6 was finally accepted and JSHint is now working properly in multi-threaded environment, so this ticket can be closed now.
